### PR TITLE
Python 3, ufo3 compatibility

### PR DESCRIPTION
**Pull request by jamesgk**
In response to @anthrotype's comments on https://github.com/googlei18n/cu2qu/pull/21

### CODE REVIEW

**Comment by anthrotype** [comment]
Thanks James. I can confirm this now works with both `trufont/defcon/python3-ufo3` branch, with `defcon/ufo3` (python2 and UFO3), and with `robofab/master` (python2 and UFO2).
:+1:

**Comment by anthrotype** [comment]
however, I still get an `ImportError: No module named robofab.pens.adapterPens` when running with `typesupply/defcon/ufo3`. So robofab is still required as a dependency when using upstream defcon/ufo3.

**Comment by jamesgk** [comment]
Thanks! Sounds like it would be good to get the upstream defcon/ufo3 updated asap.

**Comment by behdad** [comment]
@anthrotype Feel like adding a few small tests and help James hook up to Travis please?

We should send the Travis results to the fonttools group.  Same about other pieces of the stack.

**Comment by anthrotype** [comment]
Yes, good idea.

**Pull request merged**
