### PR TITLE
cu2qu.pens: make sure closed contour starts with an on-curve

### PR DESCRIPTION
**Pull request by anthrotype**
I cherry-picked commit https://github.com/googlei18n/cu2qu/pull/29/commits/3b19d07db17fe4a64ccc40984d619d242f7f4169 from #29, since the Cu2Qu pen is about to be used in ufo2ft with https://github.com/googlei18n/ufo2ft/pull/54

This ensures that any off-curves that belong to the first segment in a contour will always appear at the bottom as the contour is serialized to a *.glif file.

The result is identical (UFO spec allows both), it's just normalized so that the first point in GLIF contours are on-curves.

### CODE REVIEW

**Comment by adrientetar** [comment]
Why?

**Comment by anthrotype** [comment]
because.. it's looks nicer ;)

**Comment by adrientetar** [comment]
tbh I don't see why we are adding code to avoid doing something that's perfectly supported. e.g. Glyphs often generates UFOs with an offCurve at the beginning of the contour and I had to fix defcon _get_segments to make it work in that case. If separate offCurve does not work then there's a bug in the tooling and that is what should be fixed.

**Comment by anthrotype** [comment]
the starting point remains the same for defcon. the only difference this patch makes is when the Cu2QuPoint pen is attached to a ufoLib.glifLib.GLIFPointPen (when serializing the glif)

**Comment by anthrotype** [comment]
I understand your point about it being a legitimate contour type that tools must be able to support. What I actually find a annoying is the fact the GLIF spec allows these multiple serializations for the same contour.
Yeah, it's a normalization issue, which could probably be addressed by ufonormalizer or similar. But it doesn't hurt, does it?

**Comment by adrientetar** [comment]
> the GLIF spec allows these multiple serializations for the same contour.

As I see it, if it doesn't have the same start point then it's not the same contour.

**Comment by behdad** [comment]
Doesn't this change the start point?  Makes me feel uneasy that we are changing the contour here.  So, agree with Adrien.

**Comment by behdad** [comment]
In the future we might want to have cu2qu also return a mapping from old point numbers to new point numbers.  This can be used, for example, to map point indices that will go to ttfautohint for manual adjustments.  cc @dcrossland @lemwerg

**Comment by anthrotype** [comment]
Perhaps I didn't explain the reason for this fix enough, I didn't think this would be controversial.

My intention was not actually to normalize (weird, but still legal) contours that start with an off-curve point, like Glyphs seem to allow.

I did that because of the way the `Cu2QuPointPen` translates the input point lists into a list of segments to be converted. The pen inherit (for convenience) from one the converter pens, `BasePointToSegmentPen`, which constructs a list (of lists) of segments from the initial list (of lists) of points. For the latter, the first segment of a contour consists of the first on-curve point as well as all the off-curves leading to that. That's what the Cu2QuPoint pen receives from its base class; it no longer knows whether the first segment did start from an on-curve or not.

So when the Cu2QuPoint pen has to re-construct a list of points to be sent to the drawing PointPen, it has to push back all the leading off-curve points to the end of the point list. Because in 99% of the cases (and in all font editors I know of, except Glyphs) contours do start with an on-curve point.

I hope this is clearer now?

**Comment by lemzwerg** [comment]
I agree with Behdad and Adrien: For TrueType, starting a contour with an 'off' point happens quite frequently, saving some bytes in the `glyf` table and being more elegant sometimes.

While I can't comment on `cu2qu` at all, I strongly suggest that such outlines are handled as normal as possible.

**Comment by anthrotype** [comment]
I'm responsible for this misunderstanding.

> For TrueType, starting a contour with an 'off' point happens quite frequently

I know that TrueType contours can start with off curve points, and even only contain off-curves and no on-curves. But here we are discussing cu2qu, a library which converts cubic curves to quadratic, and which for its very nature must discard all the existing cubic off curve points, replacing them with quadratic ones. Unlike TrueType contours (where all on-curves can be implied), in PostScript (cubic) contours there must be at least one on-curve point.

I agree that when the input contour to cu2qu is already a TrueType one, ie. with only quadratic splines, cu2qu should leave it untouched (if it does not yet, I'm going to make it do so).

But when the input contour contains cubic curves (or mixed), then the Cu2QuPointPen has to first split the input list of points into a list of segments -- because the cu2qu conversion happen on segments, not points. (A line segment consists of a single on-curve, a cubic segment is two off-curves followed by one on-curve, etc).
After reconstructing the segment list, and having converted the cubic ones to quadratic, the Cu2QuPointPen has to output again points, not segments. If the original cubic contour started with an off-curve, it does not matter any more, since that original off-curve point no longer exists by now.
Since cu2qu only modifies the off-curves and does not change the on-curves, the starting point of the new quadratic contour will be the first on-curve point of the original cubic contour.
99% of the cubic contours do start with an on-curve point, and cu2qu does keep it like that.

Finally, all this talk about starting points in UFO contours does not make any difference as to the way these contours are going to be written out in the glyf table. 
The fontTools TTGlyphPen which we use to create the glyf table's contours is a "segment" pen, not a "point" pen: ie. it has `moveTo`, `lineTo`, `curveTo`, instead of `beginPath`, `addPoint` and `endPath`. Hence, we don't feed the TTGlyphPen a list of points, but a list of PostScript-like segment-drawing commands. This is accomplished by the `draw` method of a Defcon Glyph object -- which by the way, uses a similar adapter pen as the one used internally by the `Cu2QuPointPen`, i.e. `PointToSegmentPen`.

You can see that when the contour is closed, the `BasePointToSegmentPen` locate the first on-curve point, and rotates the point list so that it *ends* with an on-curve point:
https://github.com/unified-font-object/ufoLib/blob/master/Lib/ufoLib/pointPen.py#L107-L115

Accordingly, its subclass `PointToSegmentPen` will do a `moveTo` to the last point of the last segment (i.e. the one that was previously "rotated"):
https://github.com/unified-font-object/ufoLib/blob/master/Lib/ufoLib/pointPen.py#L160-L164

~~~

I like the idea of cu2qu providing a mapping from old point indexes to new ones. That would allow to use a TTA control file to hint on-curve points of a postscript contour, and have those re-mapped to the new indexes after the cu2qu conversion has taken place.

**Comment by lemzwerg** [comment]
> I like the idea of cu2qu providing a mapping from old point indexes to new ones. That would allow to use a TTA control file to hint on-curve points of a postscript contour, and have those re-mapped to the new indexes after the cu2qu conversion has taken place.

Well, being able to manipulate the 'on' points only is of limited use in ttfautohint, unfortunately, since in most cases you should rather move whole 'segments' (i.e., a sequence of 'off' and 'on' points lying more or less on a horizontal line).  On the other hand, if a point's 'left' and 'right' control point neighbors of a cubic Bezier are on a horizontal line, so are the point's 'left' and 'right' neighbors of the corresponding quadratic spline. These points would ttfautohint need, too.

**Pull request merged**
