### PR TITLE
set up PyPI deployment on tags from Travis CI

### PR DESCRIPTION
**Pull request by anthrotype**
I'm using my (encrypted) PyPI password account, but of course I'll give Behdad and James admin access to the cu2qu PyPI project page (this is created automatically on uploading the the first distributions).

Once this is merged, you can push a tag, or create a Github Release (which also pushes a tag), and Travis will automatically upload the generated sdist and wheel packages to PyPI.

This way we can specify cu2qu library as requirement for other projects, and we can install it via `pip`.

### CODE REVIEW

**Comment by khaledhosny** [comment]
Can this be merged?
(I’m trying to cleanup my dependencies and set CI for a font project, and cu2qu is the only remaining dependency not on PyPI).

**Comment by anthrotype** [comment]
Travis didn't build the 1.1.0 tag because it says 

 > Branch "1.1.0" not included per configuration

I'll deletw the tag, fix the configuration and re-tag once I'm on my laptop.

**Comment by anthrotype** [comment]
OK, it's live now:
https://pypi.org/project/cu2qu/
https://pypi.python.org/pypi/cu2qu

**Comment by khaledhosny** [comment]
Shouldn’t ufo2ft depend on compreffor? I don’t know how pip handles dependencies, but if I don’t install compreffor manually my build will [fail](https://travis-ci.org/khaledhosny/mada/builds/178631356).

**Comment by anthrotype** [comment]
I didn't add it because I thought compreffor was an "extra" optional requirement, but actually I now realize that `optimizeCff=True` by default, so you're right. I'll add it to `install_requires` in 0.2.1.

**Comment by anthrotype** [comment]
I guess I should also add cu2qu to ufo2ft's install requirements along the same lines (although one may wish to use ufo2ft for building OTFs only, and thus may not need cu2qu).

**Comment by anthrotype** [comment]
ok, I just updated ufo2ft (v0.2.1) to also require cu2qu and compreffor.

**Comment by khaledhosny** [comment]
Works fine now, thanks.

**Pull request merged**
