### PR TITLE
Remove Point class and only use built-ins

### PR DESCRIPTION
**Pull request by jamesgk**
Using built-in types (mostly tuples) seems to cut the running time
overall by about one half. Spelling out linear interpolation in the
bezier_at functions actually cuts the running time by another 10%,
but I'm not sure if it's worth it given that this code looks a bit
nicer.

Part of #9

### CODE REVIEW

**Comment by behdad** [comment]
Thanks.  How did you test this?  Can you put a perf suite together that we can easily run and measure changes?

**Comment by behdad** [comment]
Here's an example:
https://github.com/rougier/gl-bezier/blob/master/benchmark-speed.py

**Comment by behdad** [comment]
You probably should use timeit module instead.

**Comment by behdad** [comment]
> Spelling out linear interpolation in the
> bezier_at functions actually cuts the running time by another 10%,
> but I'm not sure if it's worth it given that this code looks a bit
> nicer.

After you we have a perf suite, we should look into this again.  I think by spelling out, then optimizing to reuse expressions, you can get another 10 or 20 percent.

In fact, by computing all the curve subdivision in the same run you can probably cut the time in half again.

**Comment by adrientetar** [comment]
Maybe you could try to subclass tuple to have methods still, I don't think that doing so has a speed penalty(?)

**Comment by jamesgk** [comment]
> Maybe you could try to subclass tuple to have methods still, I don't think that doing so has a speed penalty(?)

Ah, this is a nice idea!

So I ran the new benchmark code with the master branch, the optimized branch, and the master branch with Point altered to subclass tuple (and not have a `p` attribute). It seems subclassing tuple yields a very significant performance gain, but not using a class is still fastest. Here are the ballpark figures I found:

```
master:    min 0.00059s, avg 0.0020s
optimize:  min 0.00023s, avg 0.0007s
tuple sub: min 0.00030s, avg 0.0010s
```

Interesting stuff! I think the speedup of no class is still worth not using methods. But of course I'd welcome other perspectives or further experimentation.

**Comment by adrientetar** [comment]
Have you tried a class with \__slots__ where you store self.x and self.y, that's what defcon does. I'd be curious to know how it differs from the other techniques.

**Comment by behdad** [comment]
I think for cu2qu we should live with the no-class.

While discussing possible alternates, I like to suggest the namedtuple approach as well:
```python
from collections import namedtuple 
 
def struct (name, members): 
    cls = namedtuple (name, members) 
    cls.__repr__ = lambda self: "%s(%s)" % (name, ','.join(str(s) for s in self)) 
    return cls 

class Point (struct ('Point', ('x', 'y'))): 
  pass
```

**Comment by jamesgk** [comment]
Just for fun, I tried slots and named tuples. Using slots gave pretty much the same performance as subclassing tuple, using namedtuples was actually a bit slower (around `min 0.00040s, avg 0.0014s`).

**Comment by dougfelt** [comment]
Interesting, I thought namedtuples would work for this.

**Comment by behdad** [comment]
Thanks.

**Pull request merged**
