### PR TITLE
don't truncate floats but round them before casting them to ints

### PR DESCRIPTION
**Pull request by anthrotype**
First of all, thank you James and Behdad for making this available!

The core algorithm in `cubic_approx` function (at [line 120](https://github.com/googlei18n/cu2qu/blob/master/Lib/cu2qu.py#L120)) is as simple as it is elegant.

I've been testing it today and I'm already impressed by the results. I have a few comments and a small patch already (I've already signed the CLA for brotli so I presume it should apply here too).

Firstly, I would like to see this working as a Pen, in the fonttools/robofab sense. Currently, the script replaces the `objectsRF.RSegment` objects in place; this means, it doesn't work in other Robofab "worlds", e.g. `objectsFL` for example, whose objects have slightly different attributes, etc.
The pen protocol would allow the converter to abstract from the specifics of each implementation.

Second, I believe the default `max_err` of 10 is a bit too generous, and may be reduced to 2, or something like that for greater accuracy.

Furthermore, the `curve_spline_dist` function calculates the distance between the cubic and the quadratic spline at sampled values of the parameter `t`. This is not necessarily the minimum distance between the curves, as they may well have different parametrisations. I think a better approach would be to compute the projection on the quadratic spline of sampled points from the cubic. It could make it a bit slower, but surely it will be more accurate. 
I found a blog post in which they explain how to find out a point on a Quadratic Bezier which is the closest possible to another point lying outside of it:

http://blog.gludion.com/2009/08/distance-to-quadratic-bezier-curve.html 

Also, instead of taking the max error, you may wish to use the "root mean square", ie. the square root of the mean of the squares of the sampled distances.

Anyway, I'll give it more tests in the next days.
Here's a little fix to make sure floating point numbers are not truncated but rounded to the closest integer. In Python, in fact, `int(0.999999999) == 0`.

Thanks again and keep up the good work! :+1:

### CODE REVIEW

**Comment by behdad** [comment]
Thanks Cosimo!  I agree with most of your suggestions.  We decided to get this out first and then clean it up and improve the API.

**Comment by behdad** [comment]
> Furthermore, the curve_spline_dist function calculates the distance between the cubic and the quadratic spline at sampled values of the parameter t. This is not necessarily the minimum distance between the curves, as they may well have different parametrisations.

Yes, I have had wanted to find an elegant error function for us to use but haven't got to yet.

> I think a better approach would be to compute the projection on the quadratic spline of sampled points from the cubic. It could make it a bit slower, but surely it will be more accurate.

Because our algorithm preserves tangents to a great extent, the parametrizations will be very close.  So I'm fine with an error function that computes a tight upper-bound to max-t-to-t-error analytically.  That problem is very much like what I solved in GLyphy, so it's a matter of sitting down and fleshing it out.

The whole thing will be much faster if done in C++ though, Python is really not designed for these kinds of work.

Also, *if* we can add a sizeable test suite to this, that can guide experimentation in a systematic way.  Something based on https://github.com/rougier/gl-bezier perhaps?  Just the bezier generator for example.  Another option would be to extract beziers from a varied set of fonts.  Maybe we can convince one of the big foundaries to generate that list for all their fonts and open source the corpus?  DaMa for starters?

cc @rougier as FYI BTW.

> I found a blog post in which they explain how to find out a point on a Quadratic Bezier which is the closest possible to another point lying outside of it:
> 
> http://blog.gludion.com/2009/08/distance-to-quadratic-bezier-curve.html

Yeah, that's not hard to solve.

> Also, instead of taking the max error, you may wish to use the "root mean square", ie. the square root of the mean of the squares of the sampled distances.

I don't believe in mean error measures, because they trade off accuracy for efficiency.  The problem is, they can go wrong, so confidence in the results suffers.  That's a problem with https://github.com/googlefonts/fontcrunch for example.  I'm interested in hard error tolerance guarantees, such that when you set the tolerance to a value that is not visible (eg 3/1000), then you are *guaranteed* to get output that is not visibly different from the input.

That said, the error metric can definitely become an input of the conversion function.

I'll try to write up the design behind the algorithm such that we can try to improve it together.


> Anyway, I'll give it more tests in the next days.

Thanks!

> Here's a little fix to make sure floating point numbers are not truncated but rounded to the closest integer. In Python, in fact, int(0.999999999) == 0.

I wonder if we should round at all.  It's not our job.

> Thanks again and keep up the good work! :+1:

:+1:

**Comment by adrientetar** [comment]
I wonder why the code uses robofab, states it's slow and converts point objects to a custom class. FYI defcon is more geared towards that and you can pass your subclasses in the constructor e.g. `Font(pointClass=myClass)`. I assume robofab is used for compability with the rest of roboto tools, it would be tricky to mix the two because contour have segment children in robofab while defcon exposes points directly and only generates segments when asked to do so. 
Looks cool otherwise, I'll look at it when I get to TTF.

**Comment by behdad** [comment]
> I wonder why the code uses robofab, states it's slow and converts point objects to a custom class. FYI defcon is more geared towards that and you can pass your subclasses in the constructor e.g. Font(pointClass=myClass). I assume robofab is used for compability with the rest of roboto tools, it would be tricky to mix the two because contour have segment children in robofab while defcon exposes points directly and only generates segments when asked to do so.
> Looks cool otherwise, I'll look at it when I get to TTF.

We'll work that out.  Though, because we want to process multiple fonts at a time compatibly, this can't be *just* a pen.  But yes, I want to work with James to keep the core algorithm, perhaps just as a pen, in the main module, and move UFO integration code into another file.

**Comment by adrientetar** [comment]
> because we want to process multiple fonts at a time compatibly

:+1: interesting, I did think about this in detail just yet.

**Comment by anthrotype** [comment]
@jamesgk I rebased the pull request branch on the current master HEAD. I'd recommend that you either leave the coordinates as floats (and let the caller round them to int) or you round them to the closest integer, as I do here.
Truncating floats as in [L139](https://github.com/googlei18n/cu2qu/blob/master/Lib/cu2qu/__init__.py#L139) compromises the accuracy of the conversion.
Thank you.

**Comment by jamesgk** [comment]
Oh, sorry for not seeing this thread before! Thanks Cosimo.

**Comment by jamesgk** [comment]
> But yes, I want to work with James to keep the core algorithm, perhaps just as a pen, in the main module, and move UFO integration code into another file.

Ahh, I started to do the opposite of this.... I can see now how we probably want the math to be the central cu2qu module, with RoboFab/FL/Defcon submodules. If that sounds good I can move things around again.

**Comment by behdad** [comment]
> Ahh, I started to do the opposite of this.... I can see now how we probably want the math to be the central cu2qu module, with RoboFab/FL/Defcon submodules. If that sounds good I can move things around again.

Yeah, that sounds good.  Thanks.

**Pull request merged**
