### PR TITLE
UFO benchmark module

### PR DESCRIPTION
**Pull request by jamesgk**
This is kind of interesting: Robofab actually runs almost twice as fast as Defcon through the ufo module.

### CODE REVIEW

**Comment by jamesgk** [comment]
@adrientetar and I did some profiling and came up with interesting call graphs (I tried generating these with python3 as well, but didn't see any difference).

Robofab:
robofab_py2

Defcon:
defcon-py2

As you can see, a whole lot of time is spent in Defcon posting notifications. Adrien suggested we can reduce this time since we're not even subscribing to those notifications; I definitely think this is worth looking into.

**Comment by adrientetar** [comment]
cc @typesupply: defcon is 2x slower mostly because of postNotification even without subscribing to notifications.

**Comment by typesupply** [comment]
Woah! Optimizing for speed is not my expertise, so I'll definitely take any PRs or input to address this. I'll look at the code tomorrow and see if anything jumps out at me.

**Comment by typesupply** [comment]
> defcon is 2x slower mostly because of postNotification even without subscribing to notifications.

I just looked through the code in [notifications.py](https://github.com/typesupply/defcon/blob/ufo3/Lib/defcon/tools/notifications.py). The only thing that jumps out at me is that during `postNotification` notifications may be sent out for [four registry keys](https://github.com/typesupply/defcon/blob/ufo3/Lib/defcon/tools/notifications.py#L146). This is because an observer may register for `None` as the notification as an indicator that it wants to receive **all** notifications for a particular observable. Likewise if an observable is registered as `None` anything sent through `postNotification` that matches the registered notification will be posted to the observer. ([Here](https://github.com/typesupply/defcon/blob/ufo3/Lib/defcon/tools/notifications.py#L56) is my attempt at documenting that.) I probably did this to make the system very flexible. I think the only time that I have ever used it was when I wrote a notification debugger that dumped *absolutely everything*. I don't know if it is used internally*. If not, we should look into what would happen if these `None` registrations weren't allowed. That may dramatically speed up `postNotification`.

*You could test this by adding some assertions in `addObserver` and `postNotification` and then running the benchmark. That should reveal if anything is using the `None` notifications/observables.

I've opened an [issue](https://github.com/typesupply/defcon/issues/79) for brainstorming ideas on speeding things up. If you have any suggestions, I'd really appreciate hearing them.

I'm not surprised that RoboFab is faster for some things. It has a very naive, hardwired, opaque object relationship and change tracking system. Things were either changed or they weren't and there was no detail beyond that. There was also no automatic change flagging. It had to be done manually and that would climb its way up through some gnarly `getParent` calls until everything had hopefully been flagged as changed. Also, external objects didn't know when things were changed. They had to check the `dirty` state of the objects continuously. That was problematic to say the least, so when I wrote defcon I implemented the observer pattern.

**Comment by behdad** [comment]
FWIW defcon master if almost as fast as robofab.  It's the ufo3 branch of defcon that is twice slower.

**Comment by behdad** [comment]
Ok, let's follow up in https://github.com/typesupply/defcon/issues/79

**Pull request merged**
